# Generated by Django 4.1.7 on 2023-04-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_name', models.CharField(max_length=35, unique=True)),
                ('launch_date', models.DateField()),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=35, unique=True)),
                ('participant_name', models.CharField(max_length=40)),
                ('order_field', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('SURVEY', 'Survey'), ('DISCUSSION', 'Discussion'), ('DIARY', 'Diary'), ('OTHERS', 'Others')], default='SURVEY', max_length=10)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclingApp.tile')),
            ],
        ),
    ]
