# Generated by Django 4.1.7 on 2023-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclingApp', '0002_rename_description_task_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.CharField(choices=[('OFFICIAL', 'Official'), ('DRAFTS', 'Drafts'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], default='DRAFTS', max_length=10),
        ),
    ]
