# Generated by Django 4.2 on 2023-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclingApp', '0003_alter_tile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('DRAFTS', 'Drafts'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], default='DRAFTS', max_length=10),
        ),
    ]
